### ISSUE TITLE
Bad link in readme

### ISSUE THREAD

**Issue by jimburtoft** [felafax/felafax#36]
The link for the free notebook in 
https://github.com/felafax/felafax/blob/main/README.md

goes to https://colab.research.google.com/github/felarof99/felafax/blob/main/.archive/Llama3_1_8b_on_Free_Colab_TPU.ipynb which leads to 
https://github.com/felarof99/llama3-fresh/blob/main/.archive/Llama3_1_8b_on_Free_Colab_TPU.ipynb
which doesn't exist.

**Comment by felarof99** [comment]
Thank you for reporting the issue, I've fixed the broken link.
